site_name: easy_cryptography Docs
theme: readthedocs

nav:
    - Home: index.md
    - Hash: Hash.md
    - Chipher: Cipher.md
    - Old Chipher: old_chipher.md
    - Unknown module:
        - Generator class: Generator.md
        - Analyse class: Analyse.md
        - Unknown class: Unknown.md
    - Changelog: Changelog.md
    - ReadMe: base_info.md