site_name: easy_crypt Docs
theme: readthedocs

nav:
    - Home: index.md
    - Hash: Hash.md
    - Chipher: Cipher.md
    - Old Chipher: old_chipher.md
    - Changelog: Changelog.md
    - ReadMe: base_info.md